import type { Locale } from "@/i18n/config";

type FaqItem = { q: string; a: string };

const fr: FaqItem[] = [
  { q: "À quels professionnels s’adresse Medimesk ?", a: "Medimesk s’adresse aux pharmacies, cliniques, hôpitaux, parapharmacies et professionnels de santé." },
  { q: "Qu’est-ce que la PDA automatisée ?", a: "La PDA automatisée, ou préparation des doses à administrer, consiste à organiser les traitements d’un patient par jour et par moment de prise grâce à une solution technologique. À partir de l’ordonnance analysée par le pharmacien, les médicaments sont préparés sous forme de doses individualisées, identifiées et prêtes à être remises au patient, à l’aidant ou à l’établissement de soins. L’objectif est de rendre le traitement plus lisible, plus régulier et mieux sécurisé.\n\nLe principe est simple dans son intention, mais structurant dans ses effets : le bon médicament, pour le bon patient, au bon moment." },
  { q: "Pourquoi Medimesk introduit-elle la PDA automatisée au Maroc ?", a: "Derrière chaque traitement chronique, il y a une réalité quotidienne souvent sous-estimée : prendre correctement ses médicaments, tous les jours, au bon moment, dans le bon ordre, n’a rien d’évident. Cette réalité devient encore plus complexe lorsque le patient est âgé, polymédiqué, peu à l’aise avec l’écrit, accompagné par un proche, ou suivi par plusieurs prescripteurs.\n\nAu Maroc, cette question devient progressivement un enjeu de santé publique majeur. Le vieillissement de la population, la progression des maladies chroniques, la place centrale des familles dans l’accompagnement des patients fragiles et les défis liés à l’observance thérapeutique imposent de repenser l’organisation concrète de la prise médicamenteuse.\n\nC’est dans ce contexte que MEDIMESK développe la PDA automatisée — préparation des doses à administrer — au Maroc." },
  { q: "Quels patients peuvent bénéficier de la PDA ?", a: "La PDA est particulièrement utile pour les patients polymédiqués, les personnes âgées, les patients atteints de maladies chroniques ou les personnes ayant des traitements complexes. Elle peut également être utile dans des cures de compléments alimentaires.\n\nElle peut aussi aider les familles et les aidants qui accompagnent un proche au quotidien." },
  { q: "Pourquoi la PDA est-elle utile pour les patients âgés ?", a: "Le vieillissement est l’un des principaux facteurs de complexification de la prise médicamenteuse. Selon le Haut-Commissariat au Plan, la population marocaine âgée de 60 ans et plus est passée de 3,168 millions en 2014 à 5,027 millions en 2024. Elle atteindrait 5,988 millions en 2030, 7,900 millions en 2040 et 9,722 millions en 2050. En part de population, les 60 ans et plus représenteraient 13,8 % en 2024, 15,7 % en 2030, 19,5 % en 2040 et 22,9 % en 2050.\n\nCe vieillissement s’accompagne de situations très concrètes : troubles de la mémoire, déficiences visuelles, dépendance progressive, multiplicité des traitements, recours aux proches, difficultés à lire ou à comprendre une prescription.\n\nEn préparant les traitements par jour et par moment de prise, la PDA automatisée rend le schéma thérapeutique plus lisible pour le patient, plus facilement vérifiable par l’aidant et plus structuré pour le pharmacien. Pour une personne âgée polymédiquée, une préparation organisée par prise peut être plus intuitive qu’une succession de boîtes à gérer seule. L’approche proposée par Medimesk tient ainsi compte des usages réels, du niveau de littératie en santé et du rôle concret des familles dans le suivi quotidien." },
  { q: "Quel est le lien entre PDA et maladies chroniques ?", a: "Les maladies non transmissibles constituent aujourd’hui le cœur de la charge sanitaire au Maroc. Ces pathologies nécessitent des traitements longs, souvent quotidiens, parfois multiples, et une observance durable. Or c’est précisément dans la durée que les risques d’oubli, de lassitude, de confusion ou de mauvaise prise augmentent.\n\nLa PDA automatisée ne prétend pas résoudre tous les déterminants de la non-observance. Elle ne répond pas, à elle seule, au coût des traitements, aux croyances du patient, aux effets indésirables non pris en charge ou aux difficultés d’accès aux soins. En revanche, elle peut répondre à plusieurs freins pratiques : confusion entre médicaments, oubli de prise, erreur de tri, complexité de l’ordonnance, préparation manuelle par la famille ou manque de repères dans le temps." },
  { q: "La PDA réduit-elle les erreurs médicamenteuses ?", a: "La PDA peut contribuer à réduire certains risques pratiques : erreur de tri, oubli d’un médicament, confusion entre comprimés, mauvaise répartition des prises ou double prise.\n\nElle ne remplace toutefois pas l’analyse pharmaceutique ni la vigilance du professionnel de santé." },
  { q: "Pourquoi la PDA est-elle utile en cas de polymédication ?", a: "La polymédication est généralement définie comme l’usage régulier d’au moins cinq médicaments, même si les définitions varient selon les études. Elle concerne particulièrement les personnes âgées, les patients atteints de plusieurs maladies chroniques et les patients suivis par plusieurs prescripteurs.\n\nLe risque principal ne réside pas seulement dans le nombre de médicaments. Il tient surtout à la combinaison de plusieurs facteurs : interactions médicamenteuses, doublons thérapeutiques, traitements inadaptés à l’âge, mauvaise compréhension des horaires, confusion entre comprimés, renouvellements incomplets, effets indésirables interprétés comme de nouveaux symptômes, ou prescriptions ajoutées sans arrêt des traitements antérieurs.\n\nDans ces situations, la PDA automatisée transforme une liste complexe de médicaments en une séquence de prises organisées : patient par patient, jour par jour, moment de prise par moment de prise. Pour le patient, cela réduit la charge cognitive. Pour l’aidant, cela facilite la vérification. Pour le pharmacien, cela ouvre la voie à un suivi plus structuré du traitement." },
  { q: "La PDA peut-elle aider les aidants familiaux ?", a: "Au Maroc, la prise en charge des personnes âgées, fragiles ou malades repose encore largement sur les familles. Pourtant, les aidants familiaux restent souvent peu visibles dans l’organisation du soin.\n\nUn proche peut être amené à acheter les médicaments, comprendre l’ordonnance, organiser les prises, surveiller l’observance, gérer les renouvellements, accompagner le patient aux rendez-vous, repérer les effets indésirables ou arbitrer entre plusieurs prescriptions. Cette charge peut être lourde, surtout sans formation ni outil adapté.\n\nLa PDA automatisée transfère une partie de la charge de préparation vers un professionnel du médicament. Elle signifie moins de tri manuel, moins de risque de confusion et une meilleure visibilité sur les prises. Les doses individualisées permettent de vérifier plus facilement si une prise a été faite, d’identifier les prises oubliées et d’anticiper les déplacements ou périodes d’absence." },
  { q: "Pourquoi la PDA est-elle une opportunité pour les pharmacies marocaines ?", a: "Le rôle du pharmacien marocain ne se limite pas à la vente de médicaments. La dispensation inclut l’analyse de la prescription, la délivrance et la mise à disposition des informations nécessaires au bon usage du médicament. Le pharmacien intervient également dans la prévention et l’éducation pour la santé.\n\nLe Conseil de la concurrence indique que le nombre d’officines est passé de 9 185 en 2015 à 14 134 en 2024, soit une hausse de 54 %, avec environ 2 606 habitants par pharmacie. Cette densité est un atout de santé publique, mais elle s’accompagne d’une pression économique. Les médicaments de prix inférieur ou égal à 278 dirhams représentent 98,8 % du volume des ventes ; ceux de prix inférieur ou égal à 100 dirhams représentent 89,5 % des unités vendues, mais seulement 55 % de la valeur.\n\nDans ce contexte, la PDA automatisée peut repositionner progressivement l’officine autour d’un service à valeur ajoutée : organisation des prises, explication au patient, soutien aux aidants, suivi des traitements chroniques et prévention des erreurs pratiques." },
  { q: "Pour quelles pharmacies la PDA est-elle pertinente ?", a: "La PDA est pertinente pour toute pharmacie qui accompagne des patients âgés, chroniques, polymédiqués ou suivis au long cours. Elle peut être mise en place quelle que soit la taille de l’officine ou sa zone d’implantation, dès lors qu’il existe un besoin d’organisation des traitements. Medimesk accompagne chaque pharmacie selon son contexte, son volume, son équipe et ses objectifs, afin de structurer un service adapté, progressif et valorisable." },
  { q: "Une pharmacie peut-elle commencer progressivement la PDA ?", a: "Oui.\n\nUne pharmacie peut commencer avec un nombre limité de patients, structurer son service, former son équipe, puis monter progressivement en volume." },
  { q: "D’où viennent les machines PDA automatisées proposées par Medimesk ?", a: "Medimesk propose au Maroc les solutions PDA automatisées de JVM / Ti-Medi, expert international de référence dans la préparation des doses à administrer. En tant que distributeur officiel au Maroc, Medimesk rend ces technologies accessibles aux professionnels de santé marocains et les accompagne dans leur installation, leur prise en main et leur utilisation quotidienne. Ce choix garantit des machines fiables, éprouvées et conçues pour répondre aux exigences de sécurité, de traçabilité et d’efficacité attendues en pharmacie comme en établissement de santé." },
  { q: "Les machines PDA sont-elles difficiles à utiliser ?", a: "Les solutions proposées nécessitent une formation, mais elles sont conçues pour accompagner les équipes dans leur prise en main.\n\nMedimesk forme les professionnels à l’utilisation des machines, du logiciel et des bonnes pratiques de préparation." },
  { q: "Medimesk accompagne-t-elle les pharmacies après l’achat ?", a: "Oui.\n\nMedimesk accompagne les pharmacies avec l’installation, la formation des équipes, la hotline, la maintenance usuelle, un kit d’information patient et un guide d’aide à la mise en place du service." },
  { q: "Medimesk réalise-t-elle un audit complet de l’officine ?", a: "Non.\n\nMedimesk n’a pas vocation à réaliser un audit global de l’officine. Son rôle est d’accompagner le choix, l’installation, la formation et la prise en main des solutions PDA." },
  { q: "Comment présenter la PDA aux patients ?", a: "La PDA peut être présentée comme un service payant permettant d’organiser les traitements par moment de prise.\n\nElle s’adresse surtout aux patients qui prennent plusieurs médicaments, aux familles qui souhaitent être rassurées et aux aidants qui cherchent une solution plus simple au quotidien." },
  { q: "Qu’est-ce que STUDEX ?", a: "STUDEX est une marque internationale spécialisée dans les systèmes de perçage d’oreilles professionnels et les boucles de perçage hypoallergéniques.\n\nMedimesk propose cette solution aux professionnels qui souhaitent intégrer un service de perçage premium." },
  { q: "Qu’est-ce qu’Advanced Piercing avec STUDEX ?", a: "Advanced Piercing avec STUDEX est une solution de perçage professionnel proposée par Medimesk.\n\nElle permet aux pharmacies, parapharmacies et instituts de proposer un service moderne, hygiénique, précis et rassurant." },
  { q: "Le système STUDEX est-il hygiénique ?", a: "Oui.\n\nLe système repose sur des cartouches stériles à usage unique, contenant la boucle de perçage et son fermoir. Cela limite les manipulations directes et renforce l’hygiène du geste." },
  { q: "Le perçage STUDEX est-il adapté aux enfants ?", a: "Le système STUDEX est pratiquement silencieux, rapide et précis, ce qui le rend rassurant pour les enfants et les familles.\n\nLe perçage doit toujours être réalisé dans un cadre professionnel, avec les autorisations et précautions nécessaires." },
  { q: "Les boucles STUDEX sont-elles hypoallergéniques ?", a: "Oui. STUDEX propose des boucles de perçage hypoallergéniques, adaptées au premier perçage.\n\nLe choix des bijoux permet de répondre aux attentes des enfants, adolescents et adultes." },
  { q: "Medimesk forme-t-elle à l’utilisation de STUDEX ?", a: "Oui.\n\nMedimesk accompagne les professionnels dans la prise en main du système STUDEX, le geste de perçage, les conseils après-perçage et l’organisation du service." },
  { q: "Comment contacter Medimesk ?", a: "Vous pouvez contacter Medimesk via le formulaire du site pour demander une démonstration, une présentation produit, un devis ou un rappel.\n\nL’équipe vous orientera vers la solution la plus adaptée à votre activité." },
];

const en: FaqItem[] = [
  { q: "Which professionals does MediMesk serve?", a: "MediMesk serves pharmacies, clinics, hospitals, parapharmacies, and healthcare professionals." },
  { q: "What is automated PDA?", a: "Automated PDA—Preparation of Doses for Administration—uses technology to organize a patient’s treatment by day and administration time. Based on a prescription reviewed by the pharmacist, medicines are prepared as identified individual doses ready for the patient, caregiver, or care facility. The aim is to make treatment clearer, more regular, and safer.\n\nThe principle is simple but far-reaching: the right medicine, for the right patient, at the right time." },
  { q: "Why is MediMesk introducing automated PDA in Morocco?", a: "Taking medicines correctly every day, at the right time and in the right order, is not straightforward—particularly for older patients, people taking multiple medicines, patients with limited health literacy, those supported by relatives, or those seeing several prescribers.\n\nIn Morocco, population aging, chronic disease, the central role of families, and treatment-adherence challenges make this an increasingly important public-health issue. This is the context in which MediMesk is developing automated PDA in Morocco." },
  { q: "Which patients can benefit from PDA?", a: "PDA is especially useful for people taking multiple medicines, older patients, people with chronic diseases, or anyone with a complex treatment. It can also support supplement regimens and help families and caregivers assisting a relative every day." },
  { q: "Why is PDA useful for older patients?", a: "Aging is a major source of medication-management complexity. According to Morocco’s High Commission for Planning, the population aged 60 and over rose from 3.168 million in 2014 to 5.027 million in 2024 and is projected to reach 5.988 million in 2030, 7.900 million in 2040, and 9.722 million in 2050—22.9% of the population by 2050.\n\nMemory and visual difficulties, increasing dependence, multiple treatments, and difficulty reading prescriptions make daily medication management harder. By organizing treatment by day and administration time, PDA makes it clearer for patients, easier for caregivers to verify, and more structured for pharmacists." },
  { q: "How are PDA and chronic diseases connected?", a: "Non-communicable diseases account for much of Morocco’s health burden. They require long-term, often daily and multiple treatments, and sustained adherence. Over time, forgetfulness, fatigue, confusion, and incorrect use become more likely.\n\nPDA cannot solve every cause of non-adherence, such as cost, beliefs, unmanaged side effects, or access to care. It can, however, address practical barriers including medicine confusion, missed doses, sorting errors, complex prescriptions, and a lack of time-based cues." },
  { q: "Does PDA reduce medication errors?", a: "PDA can help reduce practical risks such as sorting errors, missed medicines, tablet confusion, incorrectly distributed doses, or double dosing. It does not replace pharmaceutical review or the vigilance of healthcare professionals." },
  { q: "Why is PDA useful for polypharmacy?", a: "Polypharmacy is generally defined as the regular use of at least five medicines. It particularly affects older people, patients with several chronic diseases, and those seeing multiple prescribers. Risks include interactions, duplicate therapy, unsuitable treatments, misunderstood schedules, incomplete renewals, and confusion between tablets.\n\nPDA turns a complex medicine list into an organized sequence by patient, day, and administration time—reducing cognitive load, helping caregivers verify doses, and enabling more structured pharmacist follow-up." },
  { q: "Can PDA help family caregivers?", a: "In Morocco, families still provide much of the support for older, frail, or ill people. Caregivers may purchase medicines, interpret prescriptions, organize doses, monitor adherence, manage renewals, and coordinate appointments—often without training or suitable tools.\n\nAutomated PDA transfers part of the preparation burden to a medicine professional. Individual doses reduce manual sorting, make administration easier to see, and help identify missed doses or prepare for travel and absences." },
  { q: "Why is PDA an opportunity for Moroccan pharmacies?", a: "A Moroccan pharmacist’s role extends beyond selling medicines to prescription review, dispensing, proper-use information, prevention, and health education. Pharmacy numbers rose from 9,185 in 2015 to 14,134 in 2024, increasing competitive and economic pressure.\n\nPDA can help reposition the pharmacy around a value-added service: organizing doses, explaining treatment, supporting caregivers, following chronic therapy, and preventing practical errors." },
  { q: "Which pharmacies is PDA relevant for?", a: "PDA is relevant to any pharmacy supporting older patients, people with chronic diseases, patients taking multiple medicines, or long-term patients. It can be introduced in pharmacies of any size wherever treatment organization is needed. MediMesk adapts support to each pharmacy’s context, volume, team, and objectives." },
  { q: "Can a pharmacy start PDA gradually?", a: "Yes. A pharmacy can begin with a limited number of patients, structure the service, train its team, and then increase volumes progressively." },
  { q: "Where do MediMesk’s automated PDA machines come from?", a: "MediMesk offers JVM / Ti-Medi automated PDA solutions in Morocco. As the official Moroccan distributor, MediMesk makes these proven technologies accessible and supports installation, onboarding, and daily use. The machines are designed for the safety, traceability, and efficiency required in pharmacies and healthcare facilities." },
  { q: "Are PDA machines difficult to use?", a: "The solutions require training, but they are designed to guide teams through onboarding. MediMesk trains professionals to use the machines, software, and preparation best practices." },
  { q: "Does MediMesk support pharmacies after purchase?", a: "Yes. MediMesk provides installation, team training, a support hotline, routine maintenance guidance, patient-information materials, and a guide for implementing the service." },
  { q: "Does MediMesk perform a complete pharmacy audit?", a: "No. MediMesk does not conduct a comprehensive audit of the pharmacy. Its role is to support solution selection, installation, training, and adoption." },
  { q: "How should PDA be presented to patients?", a: "PDA can be presented as a paid service that organizes treatment by administration time. It is particularly relevant to patients taking several medicines, families seeking reassurance, and caregivers looking for an easier daily solution." },
  { q: "What is STUDEX?", a: "STUDEX is an international brand specializing in professional ear-piercing systems and hypoallergenic piercing earrings. MediMesk offers the solution to professionals wishing to introduce a premium piercing service." },
  { q: "What is Advanced Piercing with STUDEX?", a: "Advanced Piercing with STUDEX is a professional piercing solution offered by MediMesk. It enables pharmacies, parapharmacies, and beauty institutes to offer a modern, hygienic, precise, and reassuring service." },
  { q: "Is the STUDEX system hygienic?", a: "Yes. It uses sterile single-use cartridges containing the piercing earring and its back, limiting direct handling and strengthening procedure hygiene." },
  { q: "Is STUDEX piercing suitable for children?", a: "The STUDEX system is virtually silent, fast, and precise, making it reassuring for children and families. Piercing must always be performed professionally with the necessary permissions and precautions." },
  { q: "Are STUDEX earrings hypoallergenic?", a: "Yes. STUDEX offers hypoallergenic piercing earrings suitable for initial piercing, with choices for children, teenagers, and adults." },
  { q: "Does MediMesk provide STUDEX training?", a: "Yes. MediMesk trains professionals in using the STUDEX system, piercing technique, aftercare advice, and service organization." },
  { q: "How can I contact MediMesk?", a: "Use the website contact form to request a demonstration, product presentation, quote, or callback. The team will guide you toward the solution best suited to your activity." },
];

export const faqContent: Record<Locale, FaqItem[]> = { fr, en };
